# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modifed_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
