# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160410_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time_finished',
            new_name='time_completed',
        ),
    ]
